### ISSUE TITLE
API randomly stops working

### ISSUE THREAD

**Issue by thefakequake** [Jeet-Chugh/pcpartscraper#2]
Sometimes the API just breaks and returns no data for some reason. I keep getting the error 'NoneType is not iterable' (which basically means no results). Give it a few hours and it suddenly starts working again.

**Comment by Jeet-Chugh** [comment]
Unfortunately, this is due to PCPARTPICKER.com's implementation of Cloudflare as protection for DDOS attacks. Sending too many requests triggers CloudFlare protection, which is unable to be bypassed. 

I will try to implement a fix using CFScrape soon, and if possible, I will push it to PyPi and commit to GitHub
